# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32)),
                ('u_password', models.CharField(max_length=256)),
                ('u_age', models.IntegerField(default=22)),
                ('u_gender', models.BooleanField(default=True)),
                ('u_tel', models.CharField(max_length=16)),
                ('u_icon', models.CharField(default='default.jpg', max_length=128)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
